-- MySQL Script generated by MySQL Workbench
-- Thu Sep 30 14:58:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema itproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema itproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `itproject` DEFAULT CHARACTER SET utf8 ;
USE `itproject` ;

-- -----------------------------------------------------
-- Table `itproject`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itproject`.`User` (
  `CustomerID` INT NOT NULL,
  `Phone` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itproject`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itproject`.`Contact` (
  `ID` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Team` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Marked` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itproject`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itproject`.`Schedule` (
  `EventID` INT NOT NULL,
  `Time` DATETIME(5) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Customer_CustomerID` INT NOT NULL,
  `Marked` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EventID`),
  INDEX `fk_Meeting_Customer1_idx` (`Customer_CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_Meeting_Customer1`
    FOREIGN KEY (`Customer_CustomerID`)
    REFERENCES `itproject`.`User` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itproject`.`Customer_has_TheContact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itproject`.`Customer_has_TheContact` (
  `Customer_CustomerID` INT NOT NULL,
  `TheContact_ContactID` INT NULL,
  PRIMARY KEY (`Customer_CustomerID`),
  INDEX `fk_Customer_has_TheContact_TheContact1_idx` (`TheContact_ContactID` ASC) VISIBLE,
  INDEX `fk_Customer_has_TheContact_Customer_idx` (`Customer_CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_has_TheContact_Customer`
    FOREIGN KEY (`Customer_CustomerID`)
    REFERENCES `itproject`.`User` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_TheContact_TheContact1`
    FOREIGN KEY (`TheContact_ContactID`)
    REFERENCES `itproject`.`Contact` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
